# Generated by Django 5.2.4 on 2025-07-06 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_backend', '0003_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_messages', to='chat_backend.quiz'),
        ),
    ]
