# Generated by Django 5.2.3 on 2025-07-06 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_backend', '0005_alter_quiz_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='options',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
